version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "CURSEFORGE"
      CF_SERVER_MOD: https://media.forgecdn.net/files/3516/954/RagnamodVI-Serverfiles-6.0.24.zip
      DIFFICULTY: normal
      ALLOW_FLIGHT: "true"
      OPS: TwentyHxte, Solawful
      MEMORY: 8G  
    tty: true
    stdin_open: true
    restart: unless-stopped
    
    volumes:
     - ./minecraft-data:/data
